//    { id: 0, name: "", description: "", unlocked: false, x: window.innerWidth / 2, y: window.innerHeight / 2, parents: [1], levelUp: 1 },
// window.innerWidth / 2 = 0
// window.innerHeight / 2 = 0
const successes = [
    { id: 1, name: "Une nouvelle vie", description: "Naître et vivre pour accomplir cette liste", unlocked: false, x: window.innerWidth / 2, y: window.innerHeight / 2, levelUp: 0, parents: [] },
    //branche 1 
    { id: 2, name: "Vie et Croissance", description: "Les succès sur la vie", unlocked: false, x: window.innerWidth / 2 + 2450, y: window.innerHeight / 2 + 1200, parents: [1], levelUp: 0 },
    { id: 3, name: "Début de décennie", description: "10e anniversaire", unlocked: false, x: window.innerWidth / 2 + 1450, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 4, name: "La vingtaine", description: "20e anniversaire", unlocked: false, x: window.innerWidth / 2 + 1450, y: window.innerHeight / 2 + 1600, parents: [3], levelUp: 1 },
    { id: 5, name: "30e anniversaire", description: "Les 30 ans", unlocked: false, x: window.innerWidth / 2 + 1450, y: window.innerHeight / 2 + 1700, parents: [4], levelUp: 1 },
    { id: 6, name: "40e anniversaire", description: "Les 40 ans", unlocked: false, x: window.innerWidth / 2 + 1450, y: window.innerHeight / 2 + 1800, parents: [5], levelUp: 1 },
    { id: 7, name: "50e anniversaire", description: "Les 50 ans", unlocked: false, x: window.innerWidth / 2 + 1450, y: window.innerHeight / 2 + 1900, parents: [6], levelUp: 1 },
    { id: 8, name: "Premier compagnon", description: "Animal de compagnie", unlocked: false, x: window.innerWidth / 2 + 1550, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 9, name: "Adopté !", description: "Adopté un animal de refuge", unlocked: false, x: window.innerWidth / 2 + 1650, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 10, name: "Semeur", description: "Cultiver à partir de graines", unlocked: false, x: window.innerWidth / 2 + 1750, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 11, name: "Planteur assidu", description: "Entretenir une plante 6 mois", unlocked: false, x: window.innerWidth / 2 + 1750, y: window.innerHeight / 2 + 1600, parents: [10], levelUp: 1 },
    { id: 12, name: "Chef en herbe", description: "Cuisiner 5 plats simples", unlocked: false, x: window.innerWidth / 2 + 1850, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 13, name: "Premier chez-soi", description: "Emménager seul(e)", unlocked: false, x: window.innerWidth / 2 + 1950, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 14, name: "Conducteur novice", description: "Première voiture", unlocked: false, x: window.innerWidth / 2 + 2050, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 15, name: "Célébration de l’amour", description: "Mariage/union", unlocked: false, x: window.innerWidth / 2 + 2750, y: window.innerHeight / 2 + 1600, parents: [23], levelUp: 1 },
    { id: 16, name: "Parenté", description: "Avoir un enfant", unlocked: false, x: window.innerWidth / 2 + 2150, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 17, name: "Écriture quotidienne", description: "Journal intime 1 mois", unlocked: false, x: window.innerWidth / 2 + 2250, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 18, name: "Minimaliste", description: "Faire un tri", unlocked: false, x: window.innerWidth / 2 + 2350, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 19, name: "Maîtrise financière", description: "Gérer un budget", unlocked: false, x: window.innerWidth / 2 + 2450, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 20, name: "Équilibre parfait", description: "Budget sans excédent pendant 6 mois", unlocked: false, x: window.innerWidth / 2 + 2450, y: window.innerHeight / 2 + 1600, parents: [19], levelUp: 1 },
    { id: 21, name: "Organisateur", description: "Première fête surprise", unlocked: false, x: window.innerWidth / 2 + 2550, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 22, name: "Propriétaire", description: "Acheter première maison", unlocked: false, x: window.innerWidth / 2 + 2650, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 23, name: "Cœur ouvert", description: "Déclaration d’amour", unlocked: false, x: window.innerWidth / 2 + 2750, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 24, name: "Indépendance", description: "Vivre seul(e) 6 mois", unlocked: false, x: window.innerWidth / 2 + 1950, y: window.innerHeight / 2 + 1600, parents: [13], levelUp: 1 },
    { id: 25, name: "Voyageur solitaire", description: "Voyage à l'étranger seul(e)", unlocked: false, x: window.innerWidth / 2 + 2850, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 26, name: "Aventure linguistique", description: "Voyager sans parler la langue", unlocked: false, x: window.innerWidth / 2 + 2950, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 27, name: "Hôte", description: "Organiser un événement", unlocked: false, x: window.innerWidth / 2 + 3050, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 28, name: "Diplômé", description: "Obtenir un diplôme", unlocked: false, x: window.innerWidth / 2 + 3150, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 29, name: "Déconnexion", description: "Week-end sans téléphone", unlocked: false, x: window.innerWidth / 2 + 3250, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 30, name: "Mémoire vivante", description: "Capsule temporelle", unlocked: false, x: window.innerWidth / 2 + 3350, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 31, name: "Libération", description: "Année sabbatique", unlocked: false, x: window.innerWidth / 2 + 3450, y: window.innerHeight / 2 + 1500, parents: [2], levelUp: 1 },
    { id: 32, name: "LA nouvelle vie", description: "Avoir fini la branche de succès \"Une nouvelle vie\"", unlocked: false, x: window.innerWidth / 2 + 2450, y: window.innerHeight / 2 + 2500, parents: [7,8,9,11,12,24,14,16,17,18,20,21,22,15,25,26,27,28,29,30,31], levelUp: 10 },
    // branche 2
    { id: 33, name: "Réussite et Objectifs", description: "Les réussites et les objectifs", unlocked: false, x: window.innerWidth / 2, y: window.innerHeight / 2 + 1200, parents: [1], levelUp: 0 },
    { id: 34, name: "Champion débutant", description: "Gagner premier concours", unlocked: false, x: window.innerWidth / 2 + 850, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 35, name: "Premiers pas", description: "Premier emploi", unlocked: false, x: window.innerWidth / 2 + 700, y: window.innerHeight / 2 + 1600, parents: [36,37], levelUp: 1 },
    { id: 36, name: "Pro en entretien", description: "Entretien réussi", unlocked: false, x: window.innerWidth / 2 + 750, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 37, name: "Professionnel", description: "Créer portfolio/CV", unlocked: false, x: window.innerWidth / 2 + 650, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 38, name: "Stabilité", description: "Travail stable 1 an", unlocked: false, x: window.innerWidth / 2 + 550, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 39, name: "Avancement", description: "Promotion au travail", unlocked: false, x: window.innerWidth / 2 + 700, y: window.innerHeight / 2 + 1700, parents: [35], levelUp: 1 },
    { id: 40, name: "Entrepreneur", description: "Créer entreprise", unlocked: false, x: window.innerWidth / 2 + 450, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 41, name: "Organisateur solidaire", description: "Projet associatif", unlocked: false, x: window.innerWidth / 2 + 350, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 42, name: "Investisseur", description: "Apprendre investir", unlocked: false, x: window.innerWidth / 2 - 350, y: window.innerHeight / 2 + 1600, parents: [52], levelUp: 1 },
    { id: 43, name: "Épargnant", description: "Économiser 1000€", unlocked: false, x: window.innerWidth / 2 + 250, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 44, name: "Économiste", description: "Économiser 5000€", unlocked: false, x: window.innerWidth / 2 + 250, y: window.innerHeight / 2 + 1600, parents: [43], levelUp: 1 },
    { id: 45, name: "Fortune en marche", description: "Économiser 10000€", unlocked: false, x: window.innerWidth / 2 + 250, y: window.innerHeight / 2 + 1700, parents: [44], levelUp: 1 },
    { id: 46, name: "Professionnel connecté", description: "Participer conférence", unlocked: false, x: window.innerWidth / 2 + 150, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 47, name: "Candidat parfait", description: "Lettre motivation parfaite", unlocked: false, x: window.innerWidth / 2 + 600, y: window.innerHeight / 2 + 1600, parents: [37], levelUp: 1 },
    { id: 48, name: "Créateur", description: "Créer blog/YT", unlocked: false, x: window.innerWidth / 2 + 50, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 49, name: "Gagnant créatif", description: "Gagner de l'argent avec un projet", unlocked: false, x: window.innerWidth / 2 - 50, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 50, name: "Initié", description: "Développer une idée", unlocked: false, x: window.innerWidth / 2 - 150, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 51, name: "Globetrotter financier", description: "Compte bancaire étranger", unlocked: false, x: window.innerWidth / 2 - 250, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 52, name: "Analyste", description: "Étudie le marché", unlocked: false, x: window.innerWidth / 2 - 350, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 53, name: "Blogueur assidu", description: "Blog 6 mois", unlocked: false, x: window.innerWidth / 2 + 50, y: window.innerHeight / 2 + 1600, parents: [48], levelUp: 1 },
    { id: 54, name: "Présentateur", description: "Pitch investisseurs", unlocked: false, x: window.innerWidth / 2 - 450, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 55, name: "Créateur de produit", description: "Lancer un produit en ligne", unlocked: false, x: window.innerWidth / 2 - 550, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 56, name: "Jobber", description: "Travail à temps partiel", unlocked: false, x: window.innerWidth / 2 - 650, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 57, name: "Guide", description: "Devenir mentor", unlocked: false, x: window.innerWidth / 2 - 750, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 58, name: "Rapporteur", description: "Rapport d'activité", unlocked: false, x: window.innerWidth / 2 - 850, y: window.innerHeight / 2 + 1500, parents: [33], levelUp: 1 },
    { id: 59, name: "Réussit ?", description: "Avoir fini la branche de succès \"Réussite et Objectifs\"", unlocked: false, x: window.innerWidth / 2, y: window.innerHeight / 2 + 2500, parents: [58,57,56,55,54,51,50,42,49,34,39,38,47,40,41,45,46,53], levelUp: 10 },
    // branche 3
    { id: 60, name: "Sport et Santé", description: "Le sport c'est LA SANTÉ!", unlocked: false, x: window.innerWidth / 2 + 2000, y: window.innerHeight / 2 - 1200, parents: [1], levelUp: 1 },
    { id: 61, name: "Vitesse de départ", description: "Courir 1 km", unlocked: false, x: window.innerWidth / 2 + 2550, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 62, name: "Coureur intermédiaire", description: "Courir 5 km", unlocked: false, x: window.innerWidth / 2 + 2550, y: window.innerHeight / 2 - 1600, parents: [61], levelUp: 1 },
    { id: 63, name: "Coureur confirmé", description: "Courir 10 km", unlocked: false, x: window.innerWidth / 2 + 2550, y: window.innerHeight / 2 - 1700, parents: [62], levelUp: 1 },
    { id: 64, name: "Pompes débutant", description: "Faire 10 pompes", unlocked: false, x: window.innerWidth / 2 + 1450, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 65, name: "Pompes avancées", description: "Faire 20 pompes", unlocked: false, x: window.innerWidth / 2 + 1450, y: window.innerHeight / 2 - 1600, parents: [64], levelUp: 1 },
    { id: 66, name: "Pompes expert", description: "Faire 50 pompes", unlocked: false, x: window.innerWidth / 2 + 1450, y: window.innerHeight / 2 - 1700, parents: [65], levelUp: 1 },
    { id: 67, name: "Pompes ultime", description: "Faire 100 pompes", unlocked: false, x: window.innerWidth / 2 + 1450, y: window.innerHeight / 2 - 1800, parents: [66], levelUp: 1 },
    { id: 68, name: "Stabilité de base", description: "Planche 1 minute", unlocked: false, x: window.innerWidth / 2 + 1550, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 69, name: "Planche pro", description: "Planche 3 minutes", unlocked: false, x: window.innerWidth / 2 + 1550, y: window.innerHeight / 2 - 1600, parents: [68], levelUp: 1 },
    { id: 70, name: "Marathonien", description: "Marathon", unlocked: false, x: window.innerWidth / 2 + 2550, y: window.innerHeight / 2 - 1800, parents: [63, 84], levelUp: 3 },
    { id: 71, name: "Nageur débutant", description: "Nager 1 km", unlocked: false, x: window.innerWidth / 2 + 1650, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 72, name: "Nageur aguerri", description: "Nager 5 km", unlocked: false, x: window.innerWidth / 2 + 1650, y: window.innerHeight / 2 - 1600, parents: [71], levelUp: 1 },
    { id: 73, name: "Cycliste débutant", description: "Apprendre à faire du vélo", unlocked: false, x: window.innerWidth / 2 + 1750, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 74, name: "Yogi débutant", description: "Yoga 1 mois", unlocked: false, x: window.innerWidth / 2 + 1950, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 75, name: "Cycliste aguerri", description: "Vélo pendant 50 Km", unlocked: false, x: window.innerWidth / 2 + 1750, y: window.innerHeight / 2 - 1600, parents: [73], levelUp: 1 },
    { id: 76, name: "Triathlète", description: "Triathlon", unlocked: false, x: window.innerWidth / 2 + 1700, y: window.innerHeight / 2 - 1800, parents: [70, 72, 75], levelUp: 5 },
    { id: 77, name: "Méditant assidu", description: "Méditation 1 mois", unlocked: false, x: window.innerWidth / 2 + 2050, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 78, name: "Régime maîtrisé", description: "Régime 6 mois", unlocked: false, x: window.innerWidth / 2 + 2150, y: window.innerHeight / 2 - 1600, parents: [85], levelUp: 1 },
    { id: 79, name: "Athlète", description: "Compétition sportive", unlocked: false, x: window.innerWidth / 2 + 1550, y: window.innerHeight / 2 - 1900, parents: [76, 67, 69], levelUp: 10 },
    { id: 80, name: "Sportif assidu", description: "Retraite sportive", unlocked: false, x: window.innerWidth / 2 + 2250, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 81, name: "Aventurier extrême", description: "Activité sportive extrême", unlocked: false, x: window.innerWidth / 2 + 2350, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 82, name: "Forme parfaite", description: "Poids de forme", unlocked: false, x: window.innerWidth / 2 + 2450, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 83, name: "Fit régulier", description: "Routine fitness 3 mois", unlocked: false, x: window.innerWidth / 2 + 2650, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 84, name: "Santé parfaite", description: "Routine santé 6 mois", unlocked: false, x: window.innerWidth / 2 + 2650, y: window.innerHeight / 2 - 1600, parents: [83], levelUp: 1 },
    { id: 85, name: "Régimé", description: "Régime 1 mois", unlocked: false, x: window.innerWidth / 2 + 2150, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 86, name: "Force de base", description: "Traction", unlocked: false, x: window.innerWidth / 2 + 1850, y: window.innerHeight / 2 - 1500, parents: [60], levelUp: 1 },
    { id: 87, name: "Relaxé", description: "Technique de relaxation", unlocked: false, x: window.innerWidth / 2 + 2000, y: window.innerHeight / 2 - 1600, parents: [74, 77], levelUp: 1 },
    { id: 88, name: "Sportif !", description: "Le sport c'est la forme avant tout !", unlocked: false, x: window.innerWidth / 2 + 2000, y: window.innerHeight / 2 - 2500, parents: [87, 79, 86, 78, 80, 81, 82], levelUp: 10 },
// 4 Branche Créativité et Art
    { id: 89, name: "Créativité et Art", description: "Branche créative et artistique", unlocked: false, x: window.innerWidth / 2 - 1950, y: window.innerHeight / 2 + 1200, parents: [1], levelUp: 0 },
// Niveau 1
    { id: 90, name: "Artiste débutant", description: "Dessiner un personnage", unlocked: false, x: window.innerWidth / 2 - 2650, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 91, name: "Peintre amateur", description: "Peindre un tableau", unlocked: false, x: window.innerWidth / 2 - 2550, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 92, name: "Compositeur débutant", description: "Composer une musique", unlocked: false, x: window.innerWidth / 2 - 1350, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 93, name: "Monteur", description: "Monter une vidéo", unlocked: false, x: window.innerWidth / 2 - 1450, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 94, name: "Artiste exposé", description: "Exposer une œuvre", unlocked: false, x: window.innerWidth / 2 - 2250, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 95, name: "Webmaster", description: "Créer un site web", unlocked: false, x: window.innerWidth / 2 - 2150, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 96, name: "Pixel artiste", description: "Dessin pixel art", unlocked: false, x: window.innerWidth / 2 - 2050, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 97, name: "Auteur de BD", description: "Créer une BD", unlocked: false, x: window.innerWidth / 2 - 1950, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 98, name: "Photographe débutant", description: "Apprendre la photo", unlocked: false, x: window.innerWidth / 2 - 1850, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 99, name: "Cinéaste", description: "Filmer professionnellement", unlocked: false, x: window.innerWidth / 2 - 1550, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 101, name: "Illustrateur", description: "Illustrer un livre", unlocked: false, x: window.innerWidth / 2 - 1750, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 102, name: "Céramiste", description: "Fabriquer céramique", unlocked: false, x: window.innerWidth / 2 - 1650, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 103, name: "Origamiste", description: "Faire des origamis", unlocked: false, x: window.innerWidth / 2 - 2450, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 104, name: "Podcaster", description: "Créer podcast", unlocked: false, x: window.innerWidth / 2 - 2350, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
    { id: 105, name: "Musicien débutant", description: "Apprendre instrument", unlocked: false, x: window.innerWidth / 2 - 1250, y: window.innerHeight / 2 + 1500, parents: [89], levelUp: 1 },
// Niveau 2
    { id: 100, name: "Cinéaste créatif", description: "Créer court-métrage", unlocked: false, x: window.innerWidth / 2 - 1500, y: window.innerHeight / 2 + 1600, parents: [93, 99], levelUp: 1 },
    { id: 106, name: "Chanteur-compositeur", description: "Composer chanson originale", unlocked: false, x: window.innerWidth / 2 - 1300, y: window.innerHeight / 2 + 1600, parents: [92, 105], levelUp: 2 },
    { id: 107, name: "Photographe créatif", description: "Série de photos thématiques", unlocked: false, x: window.innerWidth / 2 - 1800, y: window.innerHeight / 2 + 1600, parents: [98, 101], levelUp: 2 },
    { id: 108, name: "Monteur d’événements", description: "Montage vidéo événement", unlocked: false, x: window.innerWidth / 2 - 1400, y: window.innerHeight / 2 + 1600, parents: [93], levelUp: 2 },
// Succès final
    { id: 119, name: "Créateur accompli", description: "Avoir terminé la branche 'Créativité et Art'", unlocked: false, x: window.innerWidth / 2 - 1950, y: window.innerHeight / 2 + 2500, parents: [90, 91, 94, 95, 96, 97, 100, 102, 103, 104, 106, 107, 108], levelUp: 3 }
];